### ISSUE TITLE
cara pakai /data_mahasiswa/

### ISSUE THREAD

**Issue by teguhteja** [IlhamriSKY/PDDIKTI-kemdikbud-API#3]
saya coba menggunakan code 

```py
from pddiktipy import api
from pprint import pprint as p

a = api()

a.search_mahasiswa('Ida Bagus Teguh')
```

dan dapat hasil : 

```json
...
TEKNIK INFORMATIKA',
   'website-link': '/data_mahasiswa/MjA0N0Y2MjgtODBFNC00MTg1LThCMDUtMjRCNTA2OUFGNzNG'},
  {'text': 'IDA BAGUS TEGUH CIPTA MAYA NEGARA(1906330116), PT : UNIVERSITAS INDONESIA, Prodi: MAGISTER MANAJEMEN',
   'website-link': '/data_mahasiswa/RDczMTNBRjAtRkNFMi00ODMzLTkzQUUtMjFGNzYzNTkwRDQ2'},
  {'text': 'IDA BAGUS TEGUH TEJA MURTI(1729101066), PT : UNIVERSITAS PENDIDIKAN GANESHA, Prodi: IIMU KOMPUTER',
   'website-link': '/data_mahasiswa/MkI1QzBBMDAtNEJFNy00QUNFLTg0MTAtNkUxRjhBRDU3REY0'},
...
```

ini cara pakai `/data_mahasiswa/MkI1QzBBMDAtNEJFNy00QUNFLTg0MTAtNkUxRjhBRDU3REY0` seperti apa ?
karena saya coba `https://pddikti.kemdikbud.go.id/data_mahasiswa/MkI1QzBBMDAtNEJFNy00QUNFLTg0MTAtNkUxRjhBRDU3REY0` tidak mau keluar data nya. karena yang ada hasilnya :  `https://pddikti.kemdikbud.go.id/detail-mahasiswa/Ig8lXs-aszJ7Jd1Kj9fyzBug0_-DjOk1BlbUiSOuvy12tjFtOWjWYwiUUwuoeGWgeqcOWA==` 

terima kasih sebelumnya dan api nya penggunaan nya bagus

**Comment by IlhamriSKY** [comment]
Halo terimakasih sudah membuat issue, per 2 bulan lalu, pddikti sudah merubah semua akses APInya sehinga repository ini sudah tidak bisa mengambil data detail mahasiswa maupun universitas.

**Comment by teguhteja** [comment]
Terima kasih untuk balasan. 
Berarti harus mencari API lagi yang sesuai. 
Saya close untuk issue ini.

**Comment by IlhamriSKY** [comment]
@teguhteja Halo mas, untuk issue ini sudah solve ya, saya sudah berhasil mendapatkan cara akses API yang baru

Bisa di update di pypi
https://pypi.org/project/pddiktipy/


untuk tiap id didapatkan dari hasil search
